### ISSUE TITLE
PostCSS mixins with variables in a `calc()` function throw errors on build

### ISSUE THREAD

**Issue by rdimascio** [10up/10up-toolkit#111]
**Describe the bug**
When I have a mixin with variables and then use those variables in a `calc()` function, the parser throws an error and the build fails. Reproduced here - https://github.com/rdimascio/10up-toolkit/tree/try/postcss-calc-mixin-variables

```
@define-mixin aspect-ratio $width: 16, $height: 9 {
	overflow: hidden;
	position: relative;

	&::before {
		content: "";
		display: block;
		padding-bottom: calc($height / $width * 100%);
		width: 100%;
	}
}
```

```
ERROR in ./assets/css/frontend/style.css
Module build failed (from ../../node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ../../node_modules/postcss-loader/dist/cjs.js):
JisonLexerError: Lexical error on line 1: Unrecognized text.

  Erroneous area:
1: $height / $width * 100%
^..^
    at /Users/ryan/Projects/10up-toolkit/projects/10up-theme/assets/css/frontend/global/mixins.css:8:3
    at Object.parseError (/Users/ryan/Projects/10up-toolkit/node_modules/postcss-calc/dist/parser.js:1200:15)
    at Object.lexer_parseError [as parseError] (/Users/ryan/Projects/10up-toolkit/node_modules/postcss-calc/dist/parser.js:2333:44)
    at Object.lexer_next [as next] (/Users/ryan/Projects/10up-toolkit/node_modules/postcss-calc/dist/parser.js:3328:22)
    at Object.lexer_fastLex [as fastLex] (/Users/ryan/Projects/10up-toolkit/node_modules/postcss-calc/dist/parser.js:3403:18)
    at fastLex (/Users/ryan/Projects/10up-toolkit/node_modules/postcss-calc/dist/parser.js:1603:27)
    at Parser.parse (/Users/ryan/Projects/10up-toolkit/node_modules/postcss-calc/dist/parser.js:1677:30)
    at /Users/ryan/Projects/10up-toolkit/node_modules/postcss-calc/dist/lib/transform.js:33:30
    at walk (/Users/ryan/Projects/10up-toolkit/node_modules/postcss-value-parser/lib/walk.js:7:16)
    at ValueParser.walk (/Users/ryan/Projects/10up-toolkit/node_modules/postcss-value-parser/lib/index.js:18:3)
    at transformValue (/Users/ryan/Projects/10up-toolkit/node_modules/postcss-calc/dist/lib/transform.js:24:50)
    at processResult (/Users/ryan/Projects/10up-toolkit/node_modules/webpack/lib/NormalModule.js:751:19)
    at runLoaders (/Users/ryan/Projects/10up-toolkit/node_modules/webpack/lib/NormalModule.js:853:5)
    at /Users/ryan/Projects/10up-toolkit/node_modules/loader-runner/lib/LoaderRunner.js:399:11
    at /Users/ryan/Projects/10up-toolkit/node_modules/loader-runner/lib/LoaderRunner.js:251:18
    at context.callback (/Users/ryan/Projects/10up-toolkit/node_modules/loader-runner/lib/LoaderRunner.js:124:13)
    at Object.loader (/Users/ryan/Projects/10up-toolkit/node_modules/postcss-loader/dist/index.js:96:7)
```

**Steps to Reproduce**
1. `git clone git@github.com:rdimascio/10up-toolkit.git`
2. `npm i && cd projects/10up-theme && npm run build`

**Expected behavior**
Build passes without errors

**Comment by nicholasio** [comment]
Fixed by #114
