### ISSUE TITLE
Build error when used with 10up/block-components

### ISSUE THREAD

**Issue by johnwatkins0** [10up/10up-toolkit#12]
**Describe the bug**

When 10up/scripts is used in a project that's also using the ContentPicker from 10up/block-components, there is a transpile error, copied below.

I can't immediately figure out why this is happening or whether the fix needs to be here or in 10up/block-components, so I'm sharing a repo in the reproduction steps below to help debug.

```
ERROR in ./node_modules/@10up/block-components/components/ContentPicker/PickedItem.js
Module build failed (from ./node_modules/thread-loader/dist/cjs.js):
Thread Loader (Worker 0)
/Users/johnwatkins/content-picker-bug/node_modules/@10up/block-components/components/ContentPicker/PickedItem.js: importSource cannot be set when runtime is classic.
> 1 | import PropTypes from 'prop-types';
    | ^
  2 | import { safeDecodeURI, filterURLForDisplay } from '@wordpress/url';
  3 | import { decodeEntities } from '@wordpress/html-entities';
  4 | import { __ } from '@wordpress/i18n';
    at PoolWorker.fromErrorObj (/Users/johnwatkins/content-picker-bug/node_modules/thread-loader/dist/WorkerPool.js:262:12)
    at /Users/johnwatkins/content-picker-bug/node_modules/thread-loader/dist/WorkerPool.js:204:29
    at File.buildCodeFrameError (/Users/johnwatkins/content-picker-bug/node_modules/@babel/core/lib/transformation/file/file.js:250:12)
    at NodePath.buildCodeFrameError (/Users/johnwatkins/content-picker-bug/node_modules/@babel/traverse/lib/path/index.js:138:21)
    at PluginPass.enter (/Users/johnwatkins/content-picker-bug/node_modules/@babel/plugin-transform-react-jsx/lib/create-plugin.js:153:28)
    at newFn (/Users/johnwatkins/content-picker-bug/node_modules/@babel/traverse/lib/visitors.js:175:21)
    at NodePath._call (/Users/johnwatkins/content-picker-bug/node_modules/@babel/traverse/lib/path/context.js:55:20)
    at NodePath.call (/Users/johnwatkins/content-picker-bug/node_modules/@babel/traverse/lib/path/context.js:42:17)
    at NodePath.visit (/Users/johnwatkins/content-picker-bug/node_modules/@babel/traverse/lib/path/context.js:92:31)
    at TraversalContext.visitQueue (/Users/johnwatkins/content-picker-bug/node_modules/@babel/traverse/lib/context.js:116:16)
    at TraversalContext.visitSingle (/Users/johnwatkins/content-picker-bug/node_modules/@babel/traverse/lib/context.js:85:19)
    at TraversalContext.visit (/Users/johnwatkins/content-picker-bug/node_modules/@babel/traverse/lib/context.js:144:19)
 @ ./node_modules/@10up/block-components/components/ContentPicker/SortableList.js 8:0-38 14:52-62 14:66-76
 @ ./node_modules/@10up/block-components/components/ContentPicker/index.js
 @ ./node_modules/@10up/block-components/index.js
 @ ./test.js
```

**Steps to Reproduce**

1. Clone https://github.com/johnwatkins0/content-picker-test
2. Run `npm install`
3. Run `npm run watch`

**Expected behavior**

**Screenshots**

**Environment information**
 - Device: MacBook
 - OS: Mac OS latest
 - Latest versions of 10up/scripts and 10up/block-components
- Node 12.20.1
- NPM 6.14.10

**Additional context**

**Comment by johnwatkins0** [comment]
The issue could also be in `10up/babel-preset-default`

**Comment by tlovett1** [comment]
Block components has to be used in a WP environment. I think that's the problem. Maybe we need to make that clearer in the Readme

**Comment by johnwatkins0** [comment]
@tlovett1 The same issue occurs in a WP theme.

**Comment by tlovett1** [comment]
Ok, I'll test it out

**Comment by johnwatkins0** [comment]
After seeing some updates to the package over the last few days, I've updated to the latest version, and this issue is resolved. Closing.
